"""add etf_price_cache table

Revision ID: 509506d5c6b0
Revises: 7982c4ee5a5b
Create Date: 2026-07-03 00:26:39.497507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509506d5c6b0'
down_revision: Union[str, Sequence[str], None] = '7982c4ee5a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etf_price_cache',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('return_1y_pct', sa.Float(), nullable=True),
    sa.Column('return_ytd_pct', sa.Float(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('fetch_ok', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etf_price_cache')
    # ### end Alembic commands ###
